# Generated by Django 4.1.7 on 2023-03-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Umma forum haqida')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name="Ohirgi martta o'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Umma forum haqida',
                'verbose_name_plural': 'Umma forum haqida',
            },
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Aloqa uchun raqamlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': "Bog'lanish uchun",
                'verbose_name_plural': "Bog'lanish uchun",
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sektor nomini kiriting', max_length=200, unique=True, verbose_name='Sektor nomi')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Sektorlar',
                'verbose_name_plural': 'Sektorlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True, verbose_name='Ism')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram id')),
                ('user_phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Raqam')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Qator nomini kiriting', max_length=500, verbose_name='Nomi')),
                ('beg_price', models.CharField(default=0, help_text="Qatorning boshlang'ich narxini kiriting", max_length=50, verbose_name="Boshlang'ich narx")),
                ('end_price', models.CharField(default=0, help_text='Qatorning ohirgi narxini kiriting', max_length=50, verbose_name='Ohirgi narx')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('sector', models.ForeignKey(help_text='Qator sektorini tanlang', on_delete=django.db.models.deletion.CASCADE, to='iapp.sector', verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Qatorlar',
                'verbose_name_plural': 'Qatorlar',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Joy nomini kiriting', max_length=500, verbose_name='Nomi')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('price', models.CharField(default=0, help_text='Joyning narxini kiriting', max_length=50, verbose_name='narx')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('row', models.ForeignKey(help_text='Joy qatorini tanlang', on_delete=django.db.models.deletion.CASCADE, to='iapp.row', verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Joylar',
                'verbose_name_plural': 'Joylar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('Click', 'click'), ('Payme', 'payme')], max_length=20, verbose_name="To'lov turi")),
                ('total_price', models.CharField(max_length=50, verbose_name='Umumiy narx')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iapp.place', verbose_name='Joy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iapp.user', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Buyurtmalar',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
