# Generated by Django 4.1.7 on 2023-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iapp', '0004_sector_quantity_alter_row_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='beg_price',
        ),
        migrations.RemoveField(
            model_name='row',
            name='end_price',
        ),
        migrations.AddField(
            model_name='sector',
            name='beg_price',
            field=models.CharField(default=0, help_text="Sektorning boshlang'ich narxini kiriting", max_length=50, verbose_name="Boshlang'ich narx"),
        ),
        migrations.AddField(
            model_name='sector',
            name='end_price',
            field=models.CharField(default=0, help_text='Sektorning ohirgi narxini kiriting', max_length=50, verbose_name='Ohirgi narx'),
        ),
    ]
